services:
  mariadb:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - db_network

volumes:
  mariadb_data:

networks:
  db_network:
    driver: bridge